name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pf-dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: pf-dashboard/package-lock.json
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build

